version: "3.3"

services:
    webserver_repartidor:
        build: ./microservicio_repartidor
        container_name: webserver_repartidor

    webserver_restaurante:
        build: ./microservicio_restaurante
        container_name: webserver_restaurante

    webserver_cliente:
        build: ./microservicio_cliente
        container_name: webserver_cliente

    webserver_esb:
        build: ./ESB
        container_name: webserver_esb

    proxy:
        image: nginx
        container_name: proxy
        ports: 
            - 80:80
        volumes:
            - ./proxy:/etc/nginx/conf.d